name: Lua Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lua-lint:
    runs-on: ubuntu-slim

    env:
      SELENE_VERSION: "0.30.1"
      STYLUA_VERSION: "2.4.0"

    steps:
      - uses: actions/checkout@v6

      - name: Install CI Deps
        run: |
          sudo apt-get install -y unzip curl

      - name: Install Selene
        run: |
          curl -L https://github.com/Kampfkarren/selene/releases/download/${SELENE_VERSION}/selene-${SELENE_VERSION}-linux.zip -o selene.zip
          unzip selene.zip
          chmod +x selene
          sudo mv selene /usr/local/bin/

      - name: Install StyLua
        run: |
          curl -L https://github.com/JohnnyMorganz/StyLua/releases/download/v${STYLUA_VERSION}/stylua-linux-x86_64.zip -o stylua.zip
          unzip stylua.zip
          chmod +x stylua
          sudo mv stylua /usr/local/bin/

      - name: Run Selene
        run: |
          printf "\nRunning selene\n"
          selene --display-style quiet .

      - name: Run StyLua Lint
        run: |
          printf "\nRunning stylua\n"
          stylua --check --output-format summary .
